### ISSUE TITLE
How to compute the NLL of a ray depth

### ISSUE THREAD

**Issue by skyir0n** [shawn615/MixNeRF#1]
A question is raised while I read your paper.
I understood the calculation of the regularization which is based on the negative log-likelihood (NLL) of colors.
However, how could the NLL of the ray depth be obtained without its reference values (d_GT)?
Although I examined the corresponding code on GitHub, I rarely followed its logic.
Could you explain how to compute the NLL of a ray depth in detail?

**Comment by shawn615** [comment]
Hi, thanks for your interest in our paper.

We set the reference value d_GT as the input ray's ray depth, _i.e.,_  the length of the unnormalized input ray direction vector ||**d**||.
In the code, it is notated as "rendering['dirs_norm']" in train.py.
In short, our MixNeRF is trained to estimate the ray depth, which is not exactly identical but very close to the GT ray depth (_i.e.,_ original input ray depth).

**Comment by skyir0n** [comment]
> Hi, thanks for your interest in our paper.
> 
> We set the reference value d_GT as the input ray's ray depth, _i.e.,_ the length of the unnormalized input ray direction vector ||**d**||. In the code, it is notated as "rendering['dirs_norm']" in train.py. In short, our MixNeRF is trained to estimate the ray depth, which is not exactly identical but very close to the GT ray depth (_i.e.,_ original input ray depth).

Thanks for the reply.
You meant that the input ray depth represents a distance from the camera position to the pixel position.
Is it right?

**Comment by shawn615** [comment]
Although we focus on the role of the ray depth as a component for deriving the blending weight, yes it is. :)
