### ISSUE TITLE
a question about equation (7)

### ISSUE THREAD

**Issue by coldcode1** [shawn615/MixNeRF#5]
Thanks for your great work, I have some confusion in reading your paper, in section 3.3 of your paper, what is the meaning of mu(ij)d in equation (7)? Based on the context, it seems that every sampling point predicts mu(ij)d. Looking forward to your answer! Thanks!

**Comment by shawn615** [comment]
Thanks for your interest in our paper. :)

Yes, exactly as you mentioned, mu(ij)_d is predicted from every sampling point and it indicates the estimated ray depth for our proposed auxiliary task, ray depth estimation.
The ray depth is defined as the length of the unnormalized ray direction, and we model the distribution of ray depths by mixture of Laplacian along a ray, as well as the joint distribution of RGB.
